### ISSUE TITLE
POP OS Kernel 6.6 Missing NVidia-470 Drivers Error dpkg

### ISSUE THREAD

**Issue by marcelo-modolo** [pop-os/nvidia-graphics-drivers-470#20]
Hi!

After upgrade (today) kernel 6.6 breaks nvidia-driver-470 and dpkg.
With kernel 6.5 works fine.

Regards,
Marcelo Módolo

**Comment by leviport** [comment]
Ah it looks like this never got merged: https://github.com/pop-os/nvidia-graphics-drivers-470/pull/19

 Sorry about that, we'll get it released soon.

**Comment by leviport** [comment]
It has been released and should be available shortly. Thanks for the report!
